### ISSUE TITLE
It's possible to jump through walls

### ISSUE THREAD

**Issue by aerosol** [jmoon018/PacVim#33] opened 2018-05-17 14:17 UTC
with `$`, `0`, `gg` and `G`. Take that silly ghosts!

**Comment by aerosol** [comment] 2018-05-17 14:19
(please disregard if a feature and not a bug)

**Comment by yesanishhere** [comment] 2018-05-24 23:20
Can you explain what the issue is?

**Comment by pklapperich** [comment] 2018-07-05 17:48
![Start of level 0](https://user-images.githubusercontent.com/12666157/42338906-00db3092-8051-11e8-933f-e284313985fc.png)

Steps to reproduce:

1. Start Level 0 (seen in the picture above)
2. Press enter to start the level
3. Press $ 
4. The cursor jumps to the end of the line of text (right of the word climb)

![What happens](https://user-images.githubusercontent.com/12666157/42338948-21b29044-8051-11e8-83b9-5bab3a8b0062.png)

Expected behavior

Maybe this **IS** the expected behavior. In which case this issue can be closed or maybe marked as a documentation bug (there's no manpage for this project). 

But as a user, I don't expect a maze game to allow teleporting over walls. When I pressed $, I expected the cursor to jump to the furthest right place in the room. 

![My expectation](https://user-images.githubusercontent.com/12666157/42339112-a4039110-8051-11e8-8b8a-c10543d1f7fc.png)

**Comment by aerosol** [comment] 2018-07-05 21:22
Yup, sorry for submitting a vague report

**Comment by NonlinearFruit** [comment] 2018-11-08 05:15
I believe this is a feature
> You cannot move into the walls (yellow color). You must use vim motions to jump over them.

**Comment by aerosol** [comment] 2018-11-08 11:49
Thanks!

**Closed as completed** 2018-11-08 11:49 UTC
